### ISSUE TITLE
Gradle 5.5 Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor

### ISSUE THREAD

**Issue by kishoreraj05** [maiflai/gradle-scalatest#103]
With Gradle 5.5 and `com.github.maiflai:gradle-scalatest:0.24` I am getting below exception
Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.gradle.process.internal.DefaultExecActionFactory(org.gradle.api.internal.file.BaseDirFileResolver)
        at com.github.maiflai.ScalaTestAction.makeAction(ScalaTestAction.groovy:68)
        at com.github.maiflai.ScalaTestAction$makeAction.callStatic(Unknown Source)
        at com.github.maiflai.ScalaTestAction.execute(ScalaTestAction.groovy:32)
        at com.github.maiflai.ScalaTestAction.execute(ScalaTestAction.groovy)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:702)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:669)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:401)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)

**build.gradle:**
`buildscript {
    repositories {
        maven {
            url "$artifactory_base_url/public-maven-virtual"
            credentials {
                username = "${artifactory_user}"
                password = "${artifactory_password}"
            }
        }
        maven {
            url "$artifactory_base_url/eg-maven-release-local"
            credentials {
                username = "${artifactory_user}"
                password = "${artifactory_password}"
            }
        }
    }
    dependencies {
        classpath "org.scoverage:gradle-scoverage:2.5.0"
        classpath "com.github.maiflai:gradle-scalatest:0.24"
        classpath "com.amazonaws:aws-java-sdk:1.11.399"
        classpath "com.github.jengelman.gradle.plugins:shadow:4.0.4"
    }
}
....
....
dependencies {
//      scala
        compileOnly("org.scala-lang:scala-library:2.12.15")
        compileOnly("org.scala-lang:scala-reflect:2.12.15")
        compile("org.scala-lang:scala-compiler:2.12.15")
//      Spark
        compileOnly("org.apache.spark:spark-core_2.12:${rev_spark}"){
            exclude group: 'log4j'
        }
        compileOnly("org.apache.spark:spark-sql_2.12:${rev_spark}"){
            exclude group: 'log4j'

        }

        compile("io.delta:delta-core_2.12:1.0.1")
        compile("org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2")

//      Config
        compile "com.typesafe:config:1.3.2"

//      Unit Testing
        testCompile("junit:junit:${rev_junit}")
        testCompile("org.mockito:mockito-core:2.20.0")
        testCompile("org.scalatest:scalatest_2.12:3.2.11")
        testCompile("org.scalamock:scalamock_2.12:4.3.0")
        testCompile("org.scalatestplus:mockito-3-4_2.12:3.2.10.0")
        testRuntime("com.vladsch.flexmark:flexmark-all:0.34.0")

//      Scala test coverage
        scoverage "org.scoverage:scalac-scoverage-plugin_2.12.15:2.0.0-M5"
        scoverage "org.scoverage:scalac-scoverage-runtime_2.12:2.0.0-M5"

        compile("com.expedia.ers.sdp:sdp-velocity-common:1.4.0") {
            transitive = false
        }
//      AWS Dependencies
        compile("com.amazonaws:aws-java-sdk-s3:1.11.399")
        compile("com.amazonaws:aws-java-sdk-secretsmanager:1.11.399")

        // Log4j dependencies

        compile group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.17.1'
        compile group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.17.1'
        compile group: 'org.apache.logging.log4j', name: 'log4j-1.2-api', version: '2.17.1'
//        ES Dependencies
        compile("org.elasticsearch:elasticsearch-spark-20_2.12:8.1.0")
    }
`

**Comment by kishoreraj05** [comment]
I tried to build with the  `Gradle 5.5` and `com.github.maiflai:gradle-scalatest:0.24`. it giving below exception:
```
An exception or error caused a run to abort. This may have been caused by a problematic custom reporter.
java.lang.NoClassDefFoundError: com.vladsch.flexmark.util.ast.Node
        at org.scalatest.tools.ReporterFactory.createHtmlReporter(ReporterFactory.scala:194)
        at org.scalatest.tools.ReporterFactory.getReporterFromConfiguration(ReporterFactory.scala:245)
        at org.scalatest.tools.ReporterFactory.$anonfun$createReportersFromConfigurations$1(ReporterFactory.scala:254)
        at org.scalatest.tools.ReporterFactory$$Lambda$63/0x0000000000000000.apply(Unknown Source)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
        at scala.collection.TraversableLike$$Lambda$9/0x0000000000000000.apply(Unknown Source)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at org.scalatest.tools.ReporterConfigurations.foreach(ReporterConfiguration.scala:42)
        at scala.collection.TraversableLike.map(TraversableLike.scala:286)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
        at org.scalatest.tools.ReporterConfigurations.map(ReporterConfiguration.scala:42)
        at org.scalatest.tools.ReporterFactory.createReportersFromConfigurations(ReporterFactory.scala:253)
        at org.scalatest.tools.ReporterFactory.getDispatchReporter(ReporterFactory.scala:257)
        at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1480)
        at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
        at org.scalatest.tools.Runner$.main(Runner.scala:775)
        at org.scalatest.tools.Runner.main(Runner.scala)
Caused by: java.lang.ClassNotFoundException: com.vladsch.flexmark.util.ast.Node
        at java.net.URLClassLoader.findClass(URLClassLoader.java:591)
        at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:951)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:896)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:879)
        ... 21 more

FAILURE: Build failed with an exception.

```

**Comment by abbas-gadhia** [comment]
Use this to specify the flexmark dependency
`testRuntimeOnly("com.vladsch.flexmark:flexmark-all:0.62.2")`
